# Generated by Django 6.0.1 on 2026-03-02 11:39

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, help_text='Exactly 10 digits - used for login', max_length=10, unique=True, validators=[users.models.validate_phone_number])),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pan_number', models.CharField(blank=True, db_index=True, help_text='PAN format: AAAAA9999A', max_length=10, validators=[users.models.validate_pan_number])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, editable=False, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, help_text='6 digits', max_length=6, validators=[users.models.validate_pin_code])),
                ('profession', models.CharField(blank=True, choices=[('Salaried', 'Salaried'), ('Self-Employed', 'Self-Employed'), ('Business', 'Business')], max_length=100)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bureau_score', models.IntegerField(blank=True, db_index=True, help_text='Credit score 0-900', null=True)),
                ('income_mode', models.CharField(blank=True, choices=[('Cheque', 'Cheque'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')], max_length=20)),
                ('consent_taken', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users_user',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='idx_user_phone'), models.Index(fields=['pan_number'], name='idx_user_pan'), models.Index(fields=['status'], name='idx_user_status'), models.Index(fields=['bureau_score'], name='idx_user_bureau'), models.Index(fields=['created_at'], name='idx_user_created_at')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('pan_number__isnull', False), models.Q(('pan_number', ''), _negated=True)), fields=('pan_number',), name='unique_user_pan_number')],
            },
        ),
    ]
