# Generated by Django 6.0.1 on 2026-02-11 14:33

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(default='91', help_text='Country calling code', max_length=5)),
                ('phone_number', models.CharField(db_index=True, help_text='Exactly 10 digits', max_length=10, unique=True, validators=[users.models.validate_phone_number])),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True)),
                ('pan_number', models.CharField(db_index=True, help_text='PAN format: 5 letters + 4 digits (0001-9999) + 1 letter', max_length=10, validators=[users.models.validate_pan_number])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('age', models.IntegerField(blank=True, editable=False, help_text='Automatically calculated from date of birth', null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(db_index=True, help_text='Exactly 6 digits', max_length=6, validators=[users.models.validate_pin_code])),
                ('profession', models.CharField(blank=True, choices=[('Salaried', 'Salaried'), ('Self Employed', 'Self Employed'), ('Student', 'Student')], max_length=20)),
                ('monthly_income', models.PositiveIntegerField(blank=True, help_text='Monthly income in currency units', null=True)),
                ('bureau_score', models.IntegerField(blank=True, db_index=True, help_text='Credit bureau score (0-900)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(900)])),
                ('income_mode', models.CharField(blank=True, choices=[('Cheque', 'Cheque'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')], max_length=20)),
                ('consent_taken', models.BooleanField(default=False, help_text='Whether user consent has been obtained')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users_user',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='idx_phone'), models.Index(fields=['pan_number'], name='idx_pan'), models.Index(fields=['pin_code'], name='idx_pincode'), models.Index(fields=['bureau_score'], name='idx_bureau_score'), models.Index(fields=['created_at'], name='idx_created_at')],
            },
        ),
    ]
