# Generated by Django 6.0.1 on 2026-03-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='idx_user_created',
            old_name='idx_user_created_at',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='idx_user_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['profession'], name='idx_user_profession'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['pin_code'], name='idx_user_pincode'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['city'], name='idx_user_city'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['state'], name='idx_user_state'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status', 'created_at'], name='idx_status_created'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['profession', 'status'], name='idx_prof_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'status'], name='idx_active_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['bureau_score', 'status'], name='idx_bureau_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['pin_code', 'status'], name='idx_pin_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at', 'status'], name='idx_created_status'),
        ),
    ]
