# Generated by Django 6.0.1 on 2026-02-13 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='meta', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_added_date', models.DateField(auto_now_add=True, help_text='Date when user was first added')),
                ('first_added_time', models.TimeField(auto_now_add=True, help_text='Time when user was first added')),
                ('last_updated_date', models.DateField(auto_now=True, help_text='Date when user was last updated')),
                ('last_updated_time', models.TimeField(auto_now=True, help_text='Time when user was last updated')),
                ('first_login_date', models.DateField(blank=True, help_text='Date of first login', null=True)),
                ('first_login_time', models.TimeField(blank=True, help_text='Time of first login', null=True)),
                ('last_login_date', models.DateField(blank=True, help_text='Date of last login', null=True)),
                ('last_login_time', models.TimeField(blank=True, help_text='Time of last login', null=True)),
                ('latest_disbursal_date', models.DateField(blank=True, help_text='Date of latest loan disbursal', null=True)),
                ('latest_disbursal_time', models.TimeField(blank=True, help_text='Time of latest loan disbursal', null=True)),
                ('data_last_downloaded_date', models.DateField(blank=True, help_text='Date when user data was last downloaded', null=True)),
                ('data_last_downloaded_time', models.TimeField(blank=True, help_text='Time when user data was last downloaded', null=True)),
                ('status_lend001', models.CharField(blank=True, help_text='Status from Lender 001', max_length=50)),
                ('status_lend002', models.CharField(blank=True, help_text='Status from Lender 002', max_length=50)),
                ('status_lend003', models.CharField(blank=True, help_text='Status from Lender 003', max_length=50)),
                ('data_source', models.CharField(choices=[('CSV Upload', 'CSV Upload'), ('Manual Upload', 'Manual Upload'), ('API', 'API')], default='CSV Upload', help_text='How this user data was added', max_length=20)),
                ('data_attribution', models.CharField(blank=True, help_text='Name/source selected during upload', max_length=100)),
            ],
            options={
                'verbose_name': 'User Meta/Activity',
                'verbose_name_plural': 'User Meta/Activity Records',
                'db_table': 'users_meta',
                'indexes': [models.Index(fields=['first_added_date'], name='idx_meta_added_date'), models.Index(fields=['last_updated_date'], name='idx_meta_updated_date'), models.Index(fields=['latest_disbursal_date'], name='idx_meta_disbursal')],
            },
        ),
    ]
