"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
try:
    import dj_database_url
except ImportError:
    dj_database_url = None
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$d2o0n@+fo^qbld@#+ub$@i7a%d9s^ojxwdx%h&@t95ne25vx!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "crednorth.com",
    "www.crednorth.com",
    ".onrender.com",
    "localhost",
    "127.0.0.1"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',  # Custom user app - must be before other apps that use User model
    'loans',  # Loans app - contains LoanDisbursal model
    'lenders',  # Lenders app - contains Lender and LenderMIS models
    'crm_admin',  # CRM Admin app
    "rest_framework",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'backend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Development: SQLite (for local development only)
DATABASES = {"default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "OPTIONS": {
                "timeout": 30,  # 30 seconds timeout to prevent database locked errors
                "check_same_thread": False,  # Allow SQLite to be used across threads
            },
            "ATOMIC_REQUESTS": True,  # Wrap each request in a transaction
        }}

# Production: PostgreSQL on Render (required for 1M+ users)
if os.environ.get('DATABASE_URL'):
    # Use PostgreSQL from environment variable (Render.com)
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600,  # Connection pooling: keep connections alive for 10 minutes
        conn_health_checks=True,  # Verify connections are healthy
        ssl_require=True  # Require SSL for security
    )
    # Set database options
    DATABASES['default']['OPTIONS'] = {
        'connect_timeout': 10,
        'options': '-c statement_timeout=30000 -c idle_in_transaction_session_timeout=60000'
    }
    # Optimize for high concurrency
    DATABASES['default']['ATOMIC_REQUESTS'] = False  # Manage transactions manually for performance
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True  # Better for connection pooling
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
# This production code might break development mode, so we check whether we're in DEBUG mode
if not DEBUG:
    # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

    # Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
    # and renames the files with unique names for each version to support long-term caching
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Custom Authentication Backend (Passwordless)
AUTHENTICATION_BACKENDS = [
    'users.backends.PasswordlessAuthBackend',  # Custom passwordless backend
    'django.contrib.auth.backends.ModelBackend',  # Fallback for admin
]

# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# ========== FILE UPLOAD & SESSION SETTINGS FOR BULK UPLOADS ==========

# File upload settings - Allow large CSV files
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB - allows ~20k leads
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB

# Session settings - Prevent timeout during long uploads
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_SAVE_EVERY_REQUEST = True  # Keep session alive during uploads
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Cache settings - Redis for production (Render.com), Local memory for dev
if os.environ.get('REDIS_URL'):
    # Production: Redis cache for scalability (1M+ users)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.environ.get('REDIS_URL'),
            'TIMEOUT': 3600,  # 1 hour default
            'KEY_PREFIX': 'crednorth',
        }
    }
else:
    # Development: Local memory cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'TIMEOUT': 3600,  # 1 hour cache timeout
            'OPTIONS': {
                'MAX_ENTRIES': 5000
            }
        }
    }

# Request/Response settings
DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000  # Allow many fields in POST (for bulk admin actions)

# ========== PRODUCTION OPTIMIZATIONS FOR 1M+ USERS ==========

# Session optimization for scale
if os.environ.get('REDIS_URL'):
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'  # Use Redis for sessions
    SESSION_CACHE_ALIAS = 'default'
else:
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Database sessions for dev

# Logging configuration for production monitoring
if not DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'django.db.backends': {
                'handlers': ['console'],
                'level': 'WARNING',  # Only log slow queries
                'propagate': False,
            },
        },
    }
