# Generated by Django 6.0.1 on 2026-05-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadjob',
            name='check_dedupe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='created_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='current_batch',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='error_logs',
            field=models.TextField(blank=True, default='', help_text='Error summary and messages'),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='job_type',
            field=models.CharField(choices=[('user_import', 'User Import'), ('lead_processing', 'Lead Processing (Dedupe+Push)')], default='user_import', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='lenders',
            field=models.TextField(default='[]', help_text='JSON array of selected lenders'),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='result_file_path',
            field=models.TextField(blank=True, default='', help_text='Path to output CSV result file'),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='send_leads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='success_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='total_batches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='updated_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
