# Generated by Django 6.0.1 on 2026-05-10 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0002_uploadjob_check_dedupe_uploadjob_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedLeadRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, db_index=True, max_length=10)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Complete row data from CSV')),
                ('lender_selection', models.TextField(default='[]', help_text='JSON array of lenders to process for this row')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('lender_results', models.JSONField(blank=True, default=dict, help_text='Dict mapping lender name → result dict')),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_rows', to='crm_admin.uploadjob')),
            ],
            options={
                'db_table': 'crm_admin_uploaded_lead_row',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['upload_job', 'processing_status'], name='crm_admin_u_upload__fdc1ac_idx'), models.Index(fields=['upload_job', 'created_at'], name='crm_admin_u_upload__00b340_idx'), models.Index(fields=['processing_status', 'created_at'], name='crm_admin_u_process_224072_idx')],
            },
        ),
    ]
