# Generated by Django 6.0.1 on 2026-02-13 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(db_index=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pan_number', models.CharField(db_index=True, help_text='PAN format: AAAAA9999A', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, editable=False, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(help_text='6 digits', max_length=6)),
                ('profession', models.CharField(blank=True, choices=[('Salaried', 'Salaried'), ('Self Employed', 'Self Employed'), ('Student', 'Student')], max_length=20)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bureau_score', models.IntegerField(blank=True, db_index=True, help_text='Credit score 0-900', null=True)),
                ('consent_taken', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='loans.lender')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'loans_lead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanDisbursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disbursed_date', models.DateField()),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tenure_months', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(help_text='Lead for whom loan was disbursed', on_delete=django.db.models.deletion.CASCADE, related_name='disbursals', to='loans.lead')),
            ],
            options={
                'ordering': ['-disbursed_date'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone_number', 'pan_number'], name='idx_lead_phone_pan'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lender', 'status'], name='idx_lead_lender_status'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['bureau_score'], name='idx_lead_bureau'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('phone_number', 'lender'), name='unique_phone_per_lender'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('pan_number', 'lender'), name='unique_pan_per_lender'),
        ),
    ]
