# Generated by Django 6.0.1 on 2026-02-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='pan',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone_number', 'pan'], name='loans_lead_phone_n_ad4e78_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('phone_number', 'lender'), name='unique_phone_per_lender'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('pan', 'lender'), name='unique_pan_per_lender'),
        ),
    ]
