# Generated by Django 6.0.1 on 2026-02-28 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lendermis',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User linked to this MIS record (via mobile number)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loandisbursal',
            name='lead',
            field=models.ForeignKey(help_text='Lead for whom loan was disbursed', on_delete=django.db.models.deletion.CASCADE, related_name='disbursals', to='loans.lead'),
        ),
        migrations.AddIndex(
            model_name='lendermis',
            index=models.Index(fields=['mobile_number'], name='idx_mis_mobile'),
        ),
        migrations.AddIndex(
            model_name='lendermis',
            index=models.Index(fields=['lender', 'mobile_number'], name='idx_mis_lender_mobile'),
        ),
        migrations.AddIndex(
            model_name='lendermis',
            index=models.Index(fields=['lead_date'], name='idx_mis_lead_date'),
        ),
        migrations.AddIndex(
            model_name='lendermis',
            index=models.Index(fields=['disbursed_date'], name='idx_mis_disburse_date'),
        ),
        migrations.AddIndex(
            model_name='lendermis',
            index=models.Index(fields=['status'], name='idx_mis_status'),
        ),
        migrations.AddIndex(
            model_name='loandisbursal',
            index=models.Index(fields=['disbursed_date'], name='idx_disbursal_date'),
        ),
        migrations.AddIndex(
            model_name='loandisbursal',
            index=models.Index(fields=['lead', 'disbursed_date'], name='idx_lead_disbursal'),
        ),
    ]
