# Generated by Django 6.0.1 on 2026-02-13 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LenderMIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.UUIDField(help_text='Unique UUID for this MIS record', unique=True)),
                ('lead_date', models.DateField(blank=True, help_text='Date when lead was generated', null=True)),
                ('status', models.CharField(blank=True, help_text='Current status of the lead (e.g., pending, approved, rejected)', max_length=50)),
                ('ptb_status', models.CharField(blank=True, help_text='PTB (Pre-Trade Booking) status', max_length=50)),
                ('reject_date', models.DateField(blank=True, help_text='Date when lead was rejected', null=True)),
                ('utm_campaign', models.CharField(blank=True, help_text='UTM campaign parameter', max_length=200)),
                ('utm_source', models.CharField(blank=True, help_text='UTM source parameter', max_length=200)),
                ('mobile_number', models.CharField(db_index=True, help_text='Customer mobile number', max_length=10)),
                ('name', models.CharField(blank=True, help_text='Customer full name', max_length=200)),
                ('selfie_done', models.BooleanField(default=False, help_text='Whether selfie verification is completed')),
                ('aadhar_done', models.BooleanField(default=False, help_text='Whether Aadhar verification is completed')),
                ('pan_verified', models.BooleanField(default=False, help_text='Whether PAN verification is completed')),
                ('profession', models.CharField(blank=True, help_text='Customer profession', max_length=100)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Customer monthly salary', max_digits=12, null=True)),
                ('dob', models.DateField(blank=True, help_text='Customer date of birth', null=True)),
                ('pincode', models.CharField(blank=True, help_text='Customer pincode', max_length=6)),
                ('sanctioned_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Sanctioned loan amount', max_digits=12, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual loan amount', max_digits=12, null=True)),
                ('disbursed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount actually disbursed', max_digits=12, null=True)),
                ('disbursed_date', models.DateField(blank=True, help_text='Date when loan was disbursed', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When this MIS record was uploaded')),
                ('uploaded_by', models.CharField(blank=True, help_text='User who uploaded this MIS record', max_length=100)),
            ],
            options={
                'verbose_name': 'Lender MIS Record',
                'verbose_name_plural': 'Lender MIS Records',
                'db_table': 'loans_lender_mis',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='lender',
            options={'ordering': ['lender_id']},
        ),
        migrations.AddField(
            model_name='lender',
            name='lender_id',
            field=models.CharField(blank=True, help_text='Unique lender identifier (e.g., Lend001, Lend002)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='mis_first_updated_date',
            field=models.DateField(blank=True, help_text='Date of first MIS upload', null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='mis_first_updated_time',
            field=models.TimeField(blank=True, help_text='Time of first MIS upload', null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='mis_last_updated_date',
            field=models.DateField(blank=True, help_text='Date of latest MIS upload', null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='mis_last_updated_time',
            field=models.TimeField(blank=True, help_text='Time of latest MIS upload', null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='mis_updated_by',
            field=models.CharField(blank=True, help_text='User who last updated MIS', max_length=100),
        ),
        migrations.AddField(
            model_name='lender',
            name='pincodes_blacklisted',
            field=models.JSONField(blank=True, default=list, help_text='List of blacklisted pincodes (blocked)'),
        ),
        migrations.AddField(
            model_name='lender',
            name='pincodes_whitelisted',
            field=models.JSONField(blank=True, default=list, help_text='List of whitelisted pincodes (allowed)'),
        ),
        migrations.AddField(
            model_name='lender',
            name='total_approved',
            field=models.PositiveIntegerField(default=0, help_text='Total number of approved leads'),
        ),
        migrations.AddField(
            model_name='lender',
            name='total_disbursed_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total disbursed loan amount', max_digits=15),
        ),
        migrations.AddField(
            model_name='lender',
            name='total_kyc_aadhar',
            field=models.PositiveIntegerField(default=0, help_text='Total Aadhar verifications completed'),
        ),
        migrations.AddField(
            model_name='lender',
            name='total_kyc_pan',
            field=models.PositiveIntegerField(default=0, help_text='Total PAN verifications completed'),
        ),
        migrations.AddField(
            model_name='lender',
            name='total_leads',
            field=models.PositiveIntegerField(default=0, help_text='Total number of leads submitted'),
        ),
        migrations.AddField(
            model_name='lender',
            name='total_rejected',
            field=models.PositiveIntegerField(default=0, help_text='Total number of rejected leads'),
        ),
        migrations.AddField(
            model_name='lender',
            name='total_sanctioned_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total sanctioned loan amount', max_digits=15),
        ),
        migrations.AlterField(
            model_name='lender',
            name='name',
            field=models.CharField(help_text='Lender name', max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='lender',
            index=models.Index(fields=['lender_id'], name='idx_lender_id'),
        ),
        migrations.AddIndex(
            model_name='loandisbursal',
            index=models.Index(fields=['disbursed_date'], name='idx_disbursal_date'),
        ),
        migrations.AddIndex(
            model_name='loandisbursal',
            index=models.Index(fields=['lead', 'disbursed_date'], name='idx_lead_disbursal'),
        ),
        migrations.AlterModelTable(
            name='lender',
            table='loans_lender',
        ),
        migrations.AlterModelTable(
            name='loandisbursal',
            table='loans_loandisbursal',
        ),
        migrations.AddField(
            model_name='lendermis',
            name='lender',
            field=models.ForeignKey(help_text='Lender who uploaded this MIS record', on_delete=django.db.models.deletion.CASCADE, related_name='mis_records', to='loans.lender'),
        ),
        migrations.AddField(
            model_name='lendermis',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User linked to this MIS record (via mobile number)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lendermis',
            index=models.Index(fields=['mobile_number'], name='idx_mis_mobile'),
        ),
        migrations.AddIndex(
            model_name='lendermis',
            index=models.Index(fields=['lender', 'mobile_number'], name='idx_mis_lender_mobile'),
        ),
        migrations.AddIndex(
            model_name='lendermis',
            index=models.Index(fields=['lead_date'], name='idx_mis_lead_date'),
        ),
        migrations.AddIndex(
            model_name='lendermis',
            index=models.Index(fields=['disbursed_date'], name='idx_mis_disburse_date'),
        ),
        migrations.AddIndex(
            model_name='lendermis',
            index=models.Index(fields=['status'], name='idx_mis_status'),
        ),
    ]
