# Generated by Django 6.0.1 on 2026-03-02 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loandisbursal',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User for whom loan was disbursed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disbursals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loandisbursal',
            index=models.Index(fields=['disbursed_date'], name='idx_disbursal_date'),
        ),
        migrations.AddIndex(
            model_name='loandisbursal',
            index=models.Index(fields=['user', 'disbursed_date'], name='idx_user_disbursal'),
        ),
    ]
