# Generated by Django 6.0.1 on 2026-02-13 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_lendermis_alter_lender_options_lender_lender_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lead',
            name='unique_phone_per_lender',
        ),
        migrations.RemoveConstraint(
            model_name='lead',
            name='unique_pan_per_lender',
        ),
        migrations.AlterField(
            model_name='lead',
            name='lender',
            field=models.ForeignKey(blank=True, help_text='Lender to which lead has applied (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='loans.lender'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='unique_phone_number'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('pan_number',), name='unique_pan_number'),
        ),
    ]
