# Generated by Django 6.0.1 on 2026-02-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_lead_unique_phone_per_lender_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='idx_lead_lender_status',
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='idx_lead_status'),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lender',
        ),
    ]
