# Generated by Django 6.0.1 on 2026-02-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_lead_idx_lead_lender_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
