# Generated by Django 6.0.1 on 2026-03-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Lender name', max_length=200, unique=True)),
                ('total_leads', models.PositiveIntegerField(default=0, help_text='Total number of leads submitted')),
                ('total_approved', models.PositiveIntegerField(default=0, help_text='Total number of approved leads')),
                ('total_rejected', models.PositiveIntegerField(default=0, help_text='Total number of rejected leads')),
                ('total_sanctioned_loan_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total sanctioned loan amount', max_digits=15)),
                ('total_loan_amount_disbursed', models.DecimalField(decimal_places=2, default=0, help_text='Total disbursed loan amount', max_digits=15)),
                ('total_kyc_pan', models.PositiveIntegerField(default=0, help_text='Total PAN verifications completed')),
                ('total_kyc_aadhar', models.PositiveIntegerField(default=0, help_text='Total Aadhar verifications completed')),
                ('pincodes_whitelisted', models.JSONField(blank=True, default=list, help_text='List of whitelisted pincodes (allowed)')),
                ('pincodes_blacklisted', models.JSONField(blank=True, default=list, help_text='List of blacklisted pincodes (blocked)')),
                ('mis_first_updated_date', models.DateField(blank=True, help_text='Date of first MIS upload', null=True)),
                ('mis_first_updated_time', models.TimeField(blank=True, help_text='Time of first MIS upload', null=True)),
                ('mis_last_updated_date', models.DateField(blank=True, help_text='Date of latest MIS upload', null=True)),
                ('mis_last_updated_time', models.TimeField(blank=True, help_text='Time of latest MIS upload', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loans_lender',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LenderMIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.UUIDField(help_text='Unique UUID for this MIS record', unique=True)),
                ('lead_date', models.DateField(blank=True, help_text='Date when lead was generated', null=True)),
                ('status', models.CharField(blank=True, help_text='Current status of the lead (e.g., pending, approved, rejected)', max_length=50)),
                ('ptb_status', models.CharField(blank=True, help_text='PTB (Pre-Trade Booking) status', max_length=50)),
                ('reject_date', models.DateField(blank=True, help_text='Date when lead was rejected', null=True)),
                ('utm_campaign', models.CharField(blank=True, help_text='UTM campaign parameter', max_length=200)),
                ('utm_source', models.CharField(blank=True, help_text='UTM source parameter', max_length=200)),
                ('mobile_number', models.CharField(db_index=True, help_text='Customer mobile number', max_length=10)),
                ('name', models.CharField(blank=True, help_text='Customer full name', max_length=200)),
                ('selfie_done', models.BooleanField(default=False, help_text='Whether selfie verification is completed')),
                ('aadhar_done', models.BooleanField(default=False, help_text='Whether Aadhar verification is completed')),
                ('pan_verified', models.BooleanField(default=False, help_text='Whether PAN verification is completed')),
                ('profession', models.CharField(blank=True, help_text='Customer profession', max_length=100)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Customer monthly salary', max_digits=12, null=True)),
                ('dob', models.DateField(blank=True, help_text='Customer date of birth', null=True)),
                ('pincode', models.CharField(blank=True, help_text='Customer pincode', max_length=6)),
                ('sanctioned_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Sanctioned loan amount', max_digits=12, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual loan amount', max_digits=12, null=True)),
                ('disbursed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount actually disbursed', max_digits=12, null=True)),
                ('disbursed_date', models.DateField(blank=True, help_text='Date when loan was disbursed', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When this MIS record was uploaded')),
                ('uploaded_by', models.CharField(blank=True, help_text='User who uploaded this MIS record', max_length=100)),
            ],
            options={
                'verbose_name': 'Lender MIS Record',
                'verbose_name_plural': 'Lender MIS Records',
                'db_table': 'loans_lender_mis',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
