# Generated by Django 6.0.1 on 2026-03-02 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='mis_updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated MIS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lender_mis_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lendermis',
            name='lender',
            field=models.ForeignKey(help_text='Lender who uploaded this MIS record', on_delete=django.db.models.deletion.CASCADE, related_name='mis_records', to='lenders.lender'),
        ),
        migrations.AddField(
            model_name='lendermis',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User linked to this MIS record (via mobile number)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lendermis',
            index=models.Index(fields=['mobile_number'], name='idx_mis_mobile'),
        ),
        migrations.AddIndex(
            model_name='lendermis',
            index=models.Index(fields=['lender', 'mobile_number'], name='idx_mis_lender_mobile'),
        ),
        migrations.AddIndex(
            model_name='lendermis',
            index=models.Index(fields=['lead_date'], name='idx_mis_lead_date'),
        ),
        migrations.AddIndex(
            model_name='lendermis',
            index=models.Index(fields=['disbursed_date'], name='idx_mis_disburse_date'),
        ),
        migrations.AddIndex(
            model_name='lendermis',
            index=models.Index(fields=['status'], name='idx_mis_status'),
        ),
    ]
